
dataset: omniglot
num_ways: 5
num_shots: 1
meta:
  training_iterations: 10000
  batch_size: 16
  lr: 1.0e-3
inner:
  batch_size: 1
  training_iterations: 1
  lr: 0.4
logs:
  val_interval: 100
  writer_interval: 100
device: 'cpu'               # or 'gpu'