
dataset: sinusoid
meta:
  training_iterations: 50000
  batch_size: 25
  lr: 1.0e-3
inner:
  batch_size: 10
  training_iterations: 4
  lr: 1.0e-3
logs:
  test_interval: 100
  print_interval: 50
  save_interval: 1000
  writer_interval: 1

